### ISSUE TITLE
Version Bump to Vaultwarden 1.32.0

### ISSUE THREAD

**Issue by Jannik-Hm** [guerzon/vaultwarden#115]
Hey @guerzon,

would it be possible to update the vaultwarden image to the latest (v1.32.0)?

There are some CVE fixes listed in the release notes, so it would be quite nice from a security standpoint.

Are there any points **against** updating the chart?

**Comment by guerzon** [comment]
Hi @Jannik-Hm, thanks for raising this.

Users can at any time override the application version by setting the image version in their values:

```yaml
image:
  tag: "1.32.0-alpine"
```

I have now updated the default image tag to the latest one.

**Comment by Jannik-Hm** [comment]
Thank you very much for the quick response @guerzon.

Good to know about the override 😄.
