### ISSUE TITLE
Helm recommended labels

### ISSUE THREAD

**Issue by skysbsb** [guerzon/vaultwarden#22]
Hey, i noticed that u removed the standard templates used by helm, usually defined at _helpers.tpl file. Is there any reason for it?
This way helm won't be able to track its own manifests within k8s cluster.
You should at least include the [recommended ](https://v3.helm.sh/docs/chart_best_practices/labels/) labels into the generated helm manifests, such as `app.kubernetes.io/name`. `helm.sh/chart`, `app.kubernetes.io/managed-by` and `app.kubernetes.io/instance`

```
{{/*
Common labels
*/}}
{{- define "test.labels" -}}
helm.sh/chart: {{ include "test.chart" . }}
{{ include "test.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "test.selectorLabels" -}}
app.kubernetes.io/name: {{ include "test.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
```

Just a suggestion.

**Comment by guerzon** [comment]
Hi @skysbsb, thanks for the suggestion. Honestly, I can't recall how I created this file, but let me check this.

**Comment by guerzon** [comment]
Thanks @skysbsb.

**Comment by dolohow** [comment]
This breaks upgrading since you cannot modify labels of StatefulSet
