### ISSUE TITLE
Question: Should we use "default" storageclass name as default?

### ISSUE THREAD

**Issue by OrvilleQ** [guerzon/vaultwarden#29]
The template of pvc has a default value called "`default`" on `storageClassName`.

https://github.com/guerzon/vaultwarden/blob/95de29ef1926bfcffdbaed89791ef5686faeee61/charts/vaultwarden/templates/statefulset.yaml#L132

Isn't that will make pvc asking for a storage class named `default` instead of asking for a default storage class?

**Comment by guerzon** [comment]
thanks for the question @OrvilleQ. I will work on a fix, but PRs are also welcome.
