### ISSUE TITLE
Feature request: add other variables to configmap

### ISSUE THREAD

**Issue by akelge** [guerzon/vaultwarden#70]
First of all thank you for this chart and keeping it up to date.

There are some other variables that can be added to the configmap to support extra features:

- `ORG_CREATION_USERS`: list of users that can create and manage organizations;
- `SENDS_ALLOWED`: enable/disable the use of sends;
- `EMERGENCY_ACCESS_ALLOWED`: if it is possible to enable emergency access;
- `TZ`: the timezone, if we need it to be different than the one in the host

To get a full list, you can check how Gissi does it on his chart (that is abandoned apparently) at https://github.com/gissilabs/charts/tree/master/vaultwarden

**Comment by akelge** [comment]
Here is a list of the ones that are missing:
- `EMERGENCY_ACCESS_ALLOWED`: "true|false"
- `EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE`: a crontab time definition, like "0 3 * * * *"
- `EMERGENCY_REQUEST_TIMEOUT_SCHEDULE`: a crontab time definition, like"0 3 * * * *"
- `EVENTS_DAYS_RETAIN`: a duration, like "30d"
- `EXTENDED_LOGGING`: "true|false"
- `ICON_SERVICE`: "internal|external"
- `INVITATION_EXPIRATION_HOURS`: a number, like "48"
- `ORG_CREATION_USERS`: comma separated list of user email addresses
- `ORG_EVENTS_ENABLED`: "true|false"
- `REQUIRE_DEVICE_EMAIL`: "true|false"
- `SENDS_ALLOWED`: "true|false"
- `TRASH_AUTO_DELETE_DAYS`: a number, like "7"
- `TZ`: a Timezone definition, like "Europe/Madrid"

**Comment by J-roen** [comment]
I'm also missing `ORG_GROUPS_ENABLED`. Thanks in advance for adding support for extra environment variables!

**Comment by guerzon** [comment]
Hi @akelge @J-roen -- requested variables have been added to the chart.

**Comment by J-roen** [comment]
That's amazing! Is it also already possible to set `USER_ATTACHMENT_LIMIT` and `ORG_ATTACHMENT_LIMIT` in `values.yaml`? Thanks!

**Comment by guerzon** [comment]
> That's amazing! Is it also already possible to set `USER_ATTACHMENT_LIMIT` and `ORG_ATTACHMENT_LIMIT` in `values.yaml`? Thanks!

Done
