### ISSUE TITLE
Websockets should be disabled by default

### ISSUE THREAD

**Issue by PseudoResonance** [guerzon/vaultwarden#87]
As described [here](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications), WEBSOCKET_ENABLED is now false by default. When it's set to true, Vaultwarden uses the deprecated WebSocket support instead of the newer Rocket one.

**Comment by guerzon** [comment]
Hi @PseudoResonance, websockets have been removed from the chart altogether via #103.
