### ISSUE TITLE
Remove EnableServiceLinks

### ISSUE THREAD

**Issue by gecube** [guerzon/vaultwarden#91]
Hello!

By default the `enableServiceLinks` is `true`.

```
kubectl explain deployment.spec.template.spec.enableServiceLinks
GROUP:      apps
KIND:       Deployment
VERSION:    v1

FIELD: enableServiceLinks <boolean>

DESCRIPTION:
    EnableServiceLinks indicates whether information about services should be
    injected into pod's environment variables, matching the syntax of Docker
    links. Optional: Defaults to true.
```

It means that there is a bunch of unused and unnecessary ENVs inside of containers. I am kindly asking to remove it. Or to make configurable.

**Comment by guerzon** [comment]
Thanks for raising this @gecube. I have merged #118 that added support to disable service links. You could add this to your values file:

```yaml
enableServiceLinks: false
```
