### ISSUE TITLE
MFA values added in configmap instead of secrets

### ISSUE THREAD

**Issue by JoaoSangue** [guerzon/vaultwarden#96]
Hi.

I was looking at the configuration values for `yubico` and `duo` and noticed that they are being added in configmap as plain text. Ideally, they should follow the same pattern as `smtp` and `adminToken` and allow for an existing secret or use values received to create a secret.

**Comment by guerzon** [comment]
Hi @JoaoSangue, I merged #114 to address this feature request.

As a side note: my testing is limited up to making sure the right environment variables are set in the Vaultwarden container. It would be appreciated if you could verify that this works on your own environment. Thanks.

**Comment by JoaoSangue** [comment]
Hi, sorry for the late response. Just found out my notifications were turned off.

Appreciate the effort, it still works with the update. I'd like to argue that the clientId should be in a secret as well, but the secretKey is good enough for me. Thanks.
